Fixed Win32 build with Visual Studio: - Missing wmi.cpp in CMakeLists.txt - Set wmi.cpp to compile as C++ - Set project to C/CXX - Fixed undefined reference to sigar_proc_args_wmi_get